export enum SCREENS {
  LOGIN = "LOGIN",
  SIGN_UP = "SIGN_UP",
  RESET_PASS_WORD = "RESET_PASS_WORD",
  HOME = "HOME",
  PROFILE = "PROFILE",
  EDIT_PROFILE = "EDIT_PROFILE",
  DOCUMENT_EDITOR = "DOCUMENT_EDITOR",
  SEARCH = "SEARCH",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  PHONE_NUMBER = "PHONE_NUMBER",
  // Nested stack
  BOTTOM_TAB = "BOTTOM_TAB",
}
